import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import ViewInArIcon from "@mui/icons-material/ViewInAr";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Vision Dashboard",
    description: "Generated by Abdelrahman Maher",
};

export default function RootLayout({ children }) {
    return (
        <>
            <head>
                <link rel="icon" href="/dashboard.svg" />
            </head>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable}`}
                >
                    {children}
                </body>
            </html>
        </>
    );
}
